import MathQL
import Lean.Data.Json

/-!
# `graphs-small.db` — a MathQL `Database`

Source: `data/graphs-small.db` (one table `graph`, 13 598 rows, all
non-isomorphic simple graphs on up to 8 vertices). Generated by
`python/generate_graphs.py`; described in `data/graphs-small-description.md`.

The `graph` table's columns, with the MathQL query type (`Ty`) and the
semantically-typed `Obj` field they decode to:

```
column                 Ty       Obj field            Lean type
---------------------- -------- -------------------- -----------
graph6                 string   graph6               String
num_vertices           int      numVertices          Nat
num_edges              int      numEdges             Nat
degree_sequence        string   degreeSequence       List Nat      (JSON text)
min_degree             int      minDegree            Nat
max_degree             int      maxDegree            Nat
is_regular             bool     isRegular            Bool
num_components         int      numComponents        Nat
is_connected           bool     isConnected          Bool
diameter               int      diameter             Option Nat    (NULL if disconnected)
radius                 int      radius               Option Nat    (NULL if disconnected)
girth                  int      girth                Option Nat    (NULL if acyclic)
is_tree                bool     isTree               Bool
is_forest              bool     isForest             Bool
is_bipartite           bool     isBipartite          Bool
is_planar              bool     isPlanar             Bool
is_eulerian            bool     isEulerian           Bool
num_triangles          int      numTriangles         Nat
clique_number          int      cliqueNumber         Nat
independence_number    int      independenceNumber   Nat
chromatic_number       int      chromaticNumber      Nat
automorphism_count     int      automorphismCount    Nat
```
-/

namespace MathQL.GraphsSmallDB

/-- A row of the `graph` table, decoded into semantic Lean values. -/
structure Graph where
  graph6 : String
  numVertices : Nat
  numEdges : Nat
  degreeSequence : List Nat
  minDegree : Nat
  maxDegree : Nat
  isRegular : Bool
  numComponents : Nat
  isConnected : Bool
  diameter : Option Nat
  radius : Option Nat
  girth : Option Nat
  isTree : Bool
  isForest : Bool
  isBipartite : Bool
  isPlanar : Bool
  isEulerian : Bool
  numTriangles : Nat
  cliqueNumber : Nat
  independenceNumber : Nat
  chromaticNumber : Nat
  automorphismCount : Nat

/-- Decode one row, reading columns in the order of `graphColumns`/`select`. -/
def Graph.decode : SQLite.RowReader Graph := do
  let graph6 ← Column.string
  let numVertices ← Column.nat
  let numEdges ← Column.nat
  let degreeSequence ← Column.natList
  let minDegree ← Column.nat
  let maxDegree ← Column.nat
  let isRegular ← Column.bool
  let numComponents ← Column.nat
  let isConnected ← Column.bool
  let diameter ← Column.natOption
  let radius ← Column.natOption
  let girth ← Column.natOption
  let isTree ← Column.bool
  let isForest ← Column.bool
  let isBipartite ← Column.bool
  let isPlanar ← Column.bool
  let isEulerian ← Column.bool
  let numTriangles ← Column.nat
  let cliqueNumber ← Column.nat
  let independenceNumber ← Column.nat
  let chromaticNumber ← Column.nat
  let automorphismCount ← Column.nat
  return { graph6, numVertices, numEdges, degreeSequence, minDegree, maxDegree,
           isRegular, numComponents, isConnected, diameter, radius, girth,
           isTree, isForest, isBipartite, isPlanar, isEulerian, numTriangles,
           cliqueNumber, independenceNumber, chromaticNumber, automorphismCount }

/-- The queryable columns, in `decode`/`select` order: `(column name, query type, doc)`. -/
def graphColumns : List (String × Ty × String) :=
  [ ("graph6", .string, "the graph in graph6 encoding (nauty's canonical form)"),
    ("num_vertices", .int, "order: the number of vertices"),
    ("num_edges", .int, "size: the number of edges"),
    ("degree_sequence", .string, "JSON list of vertex degrees, sorted descending"),
    ("min_degree", .int, "the smallest vertex degree"),
    ("max_degree", .int, "the largest vertex degree"),
    ("is_regular", .bool, "whether all vertices have the same degree"),
    ("num_components", .int, "the number of connected components"),
    ("is_connected", .bool, "whether the graph is connected"),
    ("diameter", .int, "the greatest distance between two vertices; NULL when disconnected"),
    ("radius", .int, "the minimum vertex eccentricity; NULL when disconnected"),
    ("girth", .int, "the length of a shortest cycle; NULL when acyclic"),
    ("is_tree", .bool, "whether the graph is a tree"),
    ("is_forest", .bool, "whether the graph is a forest"),
    ("is_bipartite", .bool, "whether the graph is bipartite"),
    ("is_planar", .bool, "whether the graph is planar"),
    ("is_eulerian", .bool, "whether the graph has an Eulerian circuit"),
    ("num_triangles", .int, "the number of triangles (3-cliques)"),
    ("clique_number", .int, "the size of a largest clique"),
    ("independence_number", .int, "the size of a largest independent set"),
    ("chromatic_number", .int, "the chromatic number"),
    ("automorphism_count", .int, "the order of the automorphism group") ]

/-- The output fields: each column's value as JSON, off a decoded `Graph`. -/
def graphOutput : List (Label × (Graph → Lean.Json)) :=
  [ (.label "graph6", fun g => Lean.toJson g.graph6),
    (.label "num_vertices", fun g => Lean.toJson g.numVertices),
    (.label "num_edges", fun g => Lean.toJson g.numEdges),
    (.label "degree_sequence", fun g => Lean.toJson g.degreeSequence),
    (.label "min_degree", fun g => Lean.toJson g.minDegree),
    (.label "max_degree", fun g => Lean.toJson g.maxDegree),
    (.label "is_regular", fun g => Lean.toJson g.isRegular),
    (.label "num_components", fun g => Lean.toJson g.numComponents),
    (.label "is_connected", fun g => Lean.toJson g.isConnected),
    (.label "diameter", fun g => Lean.toJson g.diameter),
    (.label "radius", fun g => Lean.toJson g.radius),
    (.label "girth", fun g => Lean.toJson g.girth),
    (.label "is_tree", fun g => Lean.toJson g.isTree),
    (.label "is_forest", fun g => Lean.toJson g.isForest),
    (.label "is_bipartite", fun g => Lean.toJson g.isBipartite),
    (.label "is_planar", fun g => Lean.toJson g.isPlanar),
    (.label "is_eulerian", fun g => Lean.toJson g.isEulerian),
    (.label "num_triangles", fun g => Lean.toJson g.numTriangles),
    (.label "clique_number", fun g => Lean.toJson g.cliqueNumber),
    (.label "independence_number", fun g => Lean.toJson g.independenceNumber),
    (.label "chromatic_number", fun g => Lean.toJson g.chromaticNumber),
    (.label "automorphism_count", fun g => Lean.toJson g.automorphismCount) ]

/-- The `Graph` domain over the `graph` table. -/
def graphDomain : Domain where
  table := "graph"
  inputField := graphColumns.map fun (name, ty, doc) =>
    (.label name, { label := .label name, column := name, ty, doc })
  select := graphColumns.map fun (name, _, _) => name
  Obj := Graph
  toJson := fun g => Lean.Json.mkObj (graphOutput.map fun (l, f) => (l.name, f g))
  decode := Graph.decode
  outputField := graphOutput
  doc := "A finite simple graph (no loops or multiple edges), up to isomorphism."

/-- The `graphs-small.db` database: one domain, `Graph`. -/
def database : Database where
  overview := "All non-isomorphic simple graphs on up to 8 vertices (13,598 of them), \
    each annotated with standard graph invariants."
  const := []
  domain := [(.domain "Graph", graphDomain)]
  examples :=
    [ ("the trees on 5 vertices",
        json% { "domains": [["g", "Graph"]],
                "output": ["g.graph6", "g.degree_sequence"],
                "condition": "g.num_vertices == 5 && g.is_tree" }),
      ("the three graphs on 5 vertices with the most edges",
        json% { "domains": [["g", "Graph"]],
                "output": ["g.graph6", "g.num_edges"],
                "condition": "g.num_vertices == 5",
                "order": [["g.num_edges", "desc"]],
                "limit": 3 }),
      ("connected non-planar graphs, fewest vertices first",
        json% { "domains": [["g", "Graph"]],
                "output": ["g.graph6", "g.num_vertices"],
                "condition": "g.is_connected && !g.is_planar",
                "order": [["g.num_vertices", "asc"]],
                "limit": 5 }) ]

end MathQL.GraphsSmallDB
