import MathQL.Ty
import MathQL.Database
import Lean.Data.Json

/-!
# `graphs-small.db` — a MathQL `Database`

Source: `data/graphs-small.db` (one table `graph`, 13 598 rows, all
non-isomorphic simple graphs on up to 8 vertices). Generated by
`python/generate_graphs.py`; described in `data/graphs-small-description.md`.

The `graph` table's columns, with the MathQL query type (`Ty`):

```
column                 Ty        notes
---------------------- --------- ----------------------
graph6                 string
num_vertices           int
num_edges              int
degree_sequence        list int  JSON text
min_degree             int
max_degree             int
is_regular             bool
num_components         int
is_connected           bool
diameter               int       NULL when disconnected
radius                 int       NULL when disconnected
girth                  int       NULL when acyclic
is_tree                bool
is_forest              bool
is_bipartite           bool
is_planar              bool
is_eulerian            bool
num_triangles          int
clique_number          int
independence_number    int
chromatic_number       int
automorphism_count     int
```
-/

namespace MathQL.GraphsSmallDB

/-- The queryable columns, in `decode` order: `(column name, query type, doc)`. -/
def graphColumns : List (String × Ty × String) :=
  [ ("graph6", .string, "the graph in graph6 encoding (nauty's canonical form)"),
    ("num_vertices", .int, "order: the number of vertices"),
    ("num_edges", .int, "size: the number of edges"),
    ("degree_sequence", .list .int, "JSON list of vertex degrees, sorted descending"),
    ("min_degree", .int, "the smallest vertex degree"),
    ("max_degree", .int, "the largest vertex degree"),
    ("is_regular", .bool, "whether all vertices have the same degree"),
    ("num_components", .int, "the number of connected components"),
    ("is_connected", .bool, "whether the graph is connected"),
    ("diameter", .int, "the greatest distance between two vertices; undefined when disconnected"),
    ("radius", .int, "the minimum vertex eccentricity; undefined when disconnected"),
    ("girth", .int, "the length of a shortest cycle; undefined when acyclic"),
    ("is_tree", .bool, "whether the graph is a tree"),
    ("is_forest", .bool, "whether the graph is a forest"),
    ("is_bipartite", .bool, "whether the graph is bipartite"),
    ("is_planar", .bool, "whether the graph is planar"),
    ("is_eulerian", .bool, "whether the graph has an Eulerian circuit"),
    ("num_triangles", .int, "the number of triangles (3-cliques)"),
    ("clique_number", .int, "the size of a largest clique"),
    ("independence_number", .int, "the size of a largest independent set"),
    ("chromatic_number", .int, "the chromatic number"),
    ("automorphism_count", .int, "the order of the automorphism group") ]

/-- The `Graph` domain over the `graph` table. -/
def graphDomain : Schema where
  table := "graph"
  column := graphColumns.map fun (name, ty, doc) =>
    (.label name, { column := name, ty, isPrimary := name == "graph6", doc })
  foreignKey := []
  doc := "A finite simple graph (no loops or multiple edges), up to isomorphism."

/-- The `graphs-small.db` database: one domain, `Graph`. -/
def database : Database where
  overview := "All non-isomorphic simple graphs on up to 8 vertices, each \
    annotated with a selection of graph invariants."
  const := []
  domain := [(.domain "Graph", graphDomain)]
  sqlFunction := []
  postFunction := []
  examples :=
    [ ("the trees on 5 vertices",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"], ["degree_sequence", "g.degree_sequence"]],
                "condition": "g.num_vertices == 5 && g.is_tree" }),
      ("the three graphs on 5 vertices with the most edges",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"], ["num_edges", "g.num_edges"]],
                "condition": "g.num_vertices == 5",
                "order": [["g.num_edges", "desc"]],
                "limit": 3 }),
      ("connected non-planar graphs on at least 6 vertices, fewest vertices first",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"], ["num_vertices", "g.num_vertices"]],
                "condition": "g.is_connected && !g.is_planar && g.num_vertices >= 6",
                "order": [["g.num_vertices", "asc"]],
                "limit": 5 }),
      ("pairs of graphs with equally many vertices where the first has fewer edges",
        json% { "domains": [["g", "Graph"], ["h", "Graph"]],
                "output": [["first", "g.graph6"], ["second", "h.graph6"]],
                "condition": "g.num_vertices == h.num_vertices && g.num_edges < h.num_edges",
                "limit": 5 }),
      ("forests (girth undefined) on at most 4 vertices",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"]],
                "condition": "undefined g.girth && g.num_vertices <= 4",
                "limit": 5 }),
      ("bipartite or planar graphs whose diameter is defined and exceeds 2, widest first",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"], ["diameter", "g.diameter"]],
                "condition": "(g.is_bipartite || g.is_planar) && defined g.diameter && g.diameter > 2",
                "order": [["g.diameter", "desc"]],
                "limit": 5 }),
      ("the most irregular graphs, by the spread between max and min degree",
        json% { "domains": [["g", "Graph"]],
                "output": [["graph6", "g.graph6"], ["max_degree", "g.max_degree"],
                           ["min_degree", "g.min_degree"]],
                "condition": "g.max_degree != g.min_degree",
                "order": [["g.max_degree - g.min_degree", "desc"]],
                "limit": 3 }) ]

end MathQL.GraphsSmallDB
